services:
  gitweb:
    environment:
      GIT_REPO: # The Public Git Repo here.
      UPDATE_TIMER: 3600 # in seconds git will update the web files (default 3600) which is an hour. 
    image: ghcr.io/sveken/gitwebserver-alpine:latest
    ports:
      - "8080:8080"
    restart: always

